name: Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --workspace --all-targets --all

  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clippy
      run: rustup component add clippy
    - name: Run linter (clippy)
      run: cargo clippy -- -D warnings
